import { ICh5CommonAttributesForDir } from "../../ch5-common/interfaces/common/i-ch5-common-attributes-dir";
import { ICh5CommonAttributesForId } from "../../ch5-common/interfaces/common/i-ch5-common-attributes-id";
import { ICh5CommonAttributesForNoShowType } from "../../ch5-common/interfaces/common/i-ch5-common-attributes-noshowtype";
import { ICh5CommonAttributesForReceiveStateShow } from "../../ch5-common/interfaces/common/i-ch5-common-attributes-receivestateshow";
import { ICh5CommonAttributesForShow } from "../../ch5-common/interfaces/common/i-ch5-common-attributes-show";

/**
 * @ignore
 */
export interface ICh5QrCodeAttributes extends ICh5CommonAttributesForDir,
  ICh5CommonAttributesForShow,
  ICh5CommonAttributesForReceiveStateShow,
  ICh5CommonAttributesForNoShowType,
  ICh5CommonAttributesForId {
  /**
   * @documentation
   * [
   * "`color` attribute",
   * "***",
   * "Set the color for the qr code. Default value is #000000."
   * ]
   * @name color
   * @default #000000
   * @attributeType "string"
   */
  color: string;
  /**
   * @documentation
   * [
   * "`backgroundColor` attribute",
   * "***",
   * "Set the background color for the qr code. Default value is #ffffff."
   * ]
   * @name backgroundcolor
   * @default #ffffff
   * @attributeType "string"
   */
  backgroundColor: string;
  /**
   * @documentation
   * [
   * "`size` attribute",
   * "***",
   * "Set the width of the qr code. The height of the qr code will be same as width. Default value is 160 and it can range from 160 to 4000. The unit is pixel and should not be set in the attribute."
   * ]
   * @name size
   * @default 160
   * @limits [{"min": 160, "max": 4000}]
   * @attributeType "number"
   */
  size: number;
  /**
   * @documentation
   * [
   * "`qrCode` attribute",
   * "***",
   * "Sets the data stored in the QR Code image generated by the widget"
   * ]
   * @name qrcode
   * @default 
   * @attributeType "String"
   */
  qrCode: string;
  /**
   * @documentation
   * [
   * "`receiveStateQrCode` attribute",
   * "***",
   * "You may optionally select a serial join to programmatically change the data stored in the QR Code image generated by the widget."
   * ]
   * @name receivestateqrcode
   * @join {"direction": "state", "isContractName": true, "stringJoin": 1}
   * @attributeType "Join"
   */
  receiveStateQrCode: string;
}