import { ICh5CommonAttributesQrcode } from "../../ch5-common/interfaces/i-ch5-common-attributes-qrcode";


/**
 * @ignore
 */
export interface ICh5QrcodeAttributes extends ICh5CommonAttributesQrcode {
  /**
   * @documentation
   * [
   * "`qrcode` attribute",
   * "***",
   * "Qrcode"
   * ]
   * @name qrcode
   * @default 
   * @attributeType "String"
   */
  qrcode: string;
  /**
   * @documentation
   * [
   * "`receiveStateQrCode` attribute",
   * "***",
   * "select a serial join to programmatically change the data stored in the QR Code image generated by the widget."
   * ]
   * @name receivestateqrcode
   * @join {"direction": "state", "isContractName": true, "stringJoin": 1}
   * @attributeType "Join"
   */
  receiveStateQrCode: string;

}