import { ICh5CommonAttributesQrCode } from "../../ch5-common/interfaces/i-ch5-common-attributes-qrcode";


/**
 * @ignore
 */
export interface ICh5QrCodeAttributes extends ICh5CommonAttributesQrCode {
  /**
   * @documentation
   * [
   * "`qrCode` attribute",
   * "***",
   * "Sets the data stored in the QR Code image generated by the widget"
   * ]
   * @name qrcode
   * @default 
   * @attributeType "String"
   */
  qrCode: string;
  /**
   * @documentation
   * [
   * "`receiveStateQrCode` attribute",
   * "***",
   * "You may optionally select a serial join to programmatically change the data stored in the QR Code image generated by the widget."
   * ]
   * @name receivestateqrcode
   * @join {"direction": "state", "isContractName": true, "stringJoin": 1}
   * @attributeType "Join"
   */
  receiveStateQrCode: string;
}